### PR TITLE
Feature/changes

### PR DESCRIPTION
**Pull request by Steve51D**
- Added some links to specification repository
- Some tweaks for 'build from configuration' documentation.

### CODE REVIEW

**Comment by justadreamer** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/7460180714#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/8686731205#artifacts).

**Comment by justadreamer** [comment]
Hi @Jamesr51d, this is a useful albeit a bit old PR - it adds links to the spec into the documentation (for the curious readers) and also a couple example links.  I've fixed 2 links to the examples, all other links are leading to the spec and seem to be correct. 
Could you please review this PR - it's just a matter of checking if links to the spec correspond to the context where they are mentioned.  If that looks good - let's merge it.

**Review by Jamesr51d — APPROVED** [review]
The links all go to appropraite places. Would be good to address the split between website documentation and github documentation in the future.

**Pull request merged**
