### PR TITLE
Feature/small content tweaks

### PR DESCRIPTION
**Pull request by kirstin51D**
Mainly link fixing

### CODE REVIEW

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/5679955189#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/5680841210#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/5681073177#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/5738497520#artifacts).

**Review by Tracy51D — APPROVED** [review]

**Pull request merged**
