### PR TITLE
Feature/broken links

### PR DESCRIPTION
**Pull request by kirstin51D**
going through various pages to fix the broken 404 links

### CODE REVIEW

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6706791035#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6707306076#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6718878538#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6718871797#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6718941460#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6719008417#artifacts).

**Comment by Automation51D** [comment]
Preview available [here](https://github.com/51degrees/documentation/actions/runs/6719071431#artifacts).

**Review by Tracy51D — APPROVED** [review]
Verified relevant links are working and those they shouldn't be a link aren't.

**Pull request merged**
